server:
  port: 9191

spring:
  application:
    name: gateway
  cloud:
    consul:
      config:
        enabled: false
      #      host: 127.0.0.1
      host: consul
      port: 8500
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthFilter

        #          filters:
        #            - name: CircuitBreaker
        #              args:
        #                name: userServiceCB
        #                fallbackUri: forward:/fallback/user-service

        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/v1/books/**
          filters:
            - AuthFilter

        - id: auth-server
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - AuthFilter
jwt:
  secret: AvHGRK8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadweheufHNyG

